import Head from "next/head";
import Link from "next/link";

import UserForm from "@/components/UserForm";

import VerticalLayout from "@/layout/VerticalLayout";

export default function Home() {
  return (
    <VerticalLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section>
        <h1>Next App</h1>
        <ul>
          <Link href="/">
            <li>Home</li>
          </Link>
          <Link href="/about">
            <li>About</li>
          </Link>
          <Link href="/user">
            <li>Users</li>
          </Link>
        </ul>
      </section>

      <section>
        <UserForm />
      </section>
    </VerticalLayout>
  );
}
